-- ============================================================================
-- Script: star_schema.sql
-- Descrição: DDL completo do modelo dimensional Snowflake para Mortalidade Materna
--            PostgreSQL 12+ / SQLAlchemy compatível
-- Autor: Gerado automaticamente a partir do plano_de_implementacao.md
-- Data: 2026-07-30
-- ============================================================================
-- Fase 1: Modelagem SQL e criação das tabelas
-- 20 tabelas (14 dimensões + 5 sub-dimensões CNES + 1 fato) + 1 tabela de metadados
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Schema dimensional (isolamento do staging)
-- ---------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS dimensional;

-- ============================================================================
-- 1. HIERARQUIA GEOGRÁFICA (Snowflake)
-- ============================================================================

-- 1.1 Dim_Regiao
CREATE TABLE dimensional.dim_regiao (
    id_regiao      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_regiao    VARCHAR(20) NOT NULL,
    CONSTRAINT uq_dim_regiao_nome UNIQUE (nome_regiao)
);

COMMENT ON TABLE dimensional.dim_regiao IS 'Regiões do Brasil: Norte, Nordeste, Sudeste, Sul, Centro-Oeste';
COMMENT ON COLUMN dimensional.dim_regiao.nome_regiao IS 'Norte, Nordeste, Sudeste, Sul, Centro-Oeste';

-- 1.2 Dim_UF
CREATE TABLE dimensional.dim_uf (
    id_uf          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_uf        VARCHAR(50) NOT NULL,
    sigla_uf       CHAR(2) NOT NULL,
    id_regiao      INTEGER NOT NULL REFERENCES dimensional.dim_regiao(id_regiao) ON DELETE RESTRICT,
    CONSTRAINT uq_dim_uf_sigla UNIQUE (sigla_uf),
    CONSTRAINT uq_dim_uf_nome UNIQUE (nome_uf)
);

CREATE INDEX idx_dim_uf_id_regiao ON dimensional.dim_uf(id_regiao);

COMMENT ON TABLE dimensional.dim_uf IS 'Unidades da Federação';

-- 1.3 Dim_Municipio
CREATE TABLE dimensional.dim_municipio (
    id_municipio       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_ibge        VARCHAR(7) NOT NULL,
    nome_municipio     VARCHAR(100) NOT NULL,
    id_uf              INTEGER NOT NULL REFERENCES dimensional.dim_uf(id_uf) ON DELETE RESTRICT,
    CONSTRAINT uq_dim_municipio_codigo UNIQUE (codigo_ibge)
);

CREATE INDEX idx_dim_municipio_id_uf ON dimensional.dim_municipio(id_uf);
CREATE INDEX idx_dim_municipio_nome ON dimensional.dim_municipio(nome_municipio);

COMMENT ON TABLE dimensional.dim_municipio IS 'Municípios brasileiros (código IBGE 7 dígitos)';
COMMENT ON COLUMN dimensional.dim_municipio.codigo_ibge IS 'Código IBGE de 7 dígitos';

-- ============================================================================
-- 2. SUB-DIMENSÕES CNES (Snowflake)
-- ============================================================================

-- 2.1 Dim_NaturezaOrganizacao
CREATE TABLE dimensional.dim_natureza_organizacao (
    id_natureza_organizacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                  VARCHAR(20) NOT NULL,
    descricao               VARCHAR(255),
    CONSTRAINT uq_dim_natureza_org_codigo UNIQUE (codigo)
);

-- 2.2 Dim_TipoGestao
CREATE TABLE dimensional.dim_tipo_gestao (
    id_tipo_gestao  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(1) NOT NULL,
    descricao       VARCHAR(100),
    CONSTRAINT uq_dim_tipo_gestao_codigo UNIQUE (codigo)
);

COMMENT ON COLUMN dimensional.dim_tipo_gestao.codigo IS 'E=Estadual, M=Municipal, D=Dupla';

-- 2.3 Dim_NivelHierarquia
CREATE TABLE dimensional.dim_nivel_hierarquia (
    id_nivel_hierarquia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(20) NOT NULL,
    descricao           VARCHAR(255),
    CONSTRAINT uq_dim_nivel_hierarquia_codigo UNIQUE (codigo)
);

-- 2.4 Dim_EsferaAdministrativa
CREATE TABLE dimensional.dim_esfera_administrativa (
    id_esfera_administrativa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                   VARCHAR(20) NOT NULL,
    descricao                VARCHAR(255),
    CONSTRAINT uq_dim_esfera_admin_codigo UNIQUE (codigo)
);

-- 2.5 Dim_TipoUnidade
CREATE TABLE dimensional.dim_tipo_unidade (
    id_tipo_unidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(20) NOT NULL,
    descricao       VARCHAR(255),
    CONSTRAINT uq_dim_tipo_unidade_codigo UNIQUE (codigo)
);

-- 2.6 Dim_NaturezaJuridica
CREATE TABLE dimensional.dim_natureza_juridica (
    id_natureza_juridica INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo               VARCHAR(20) NOT NULL,
    descricao            VARCHAR(255),
    CONSTRAINT uq_dim_natureza_juridica_codigo UNIQUE (codigo)
);

-- ============================================================================
-- 3. Dim_EstabelecimentoSaude
-- ============================================================================
CREATE TABLE dimensional.dim_estabelecimento_saude (
    id_estabelecimento          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_cnes                 VARCHAR(7) NOT NULL,
    nome_estabelecimento        VARCHAR(255),
    id_municipio                INTEGER REFERENCES dimensional.dim_municipio(id_municipio) ON DELETE RESTRICT,
    id_natureza_organizacao     INTEGER REFERENCES dimensional.dim_natureza_organizacao(id_natureza_organizacao) ON DELETE RESTRICT,
    id_tipo_gestao              INTEGER REFERENCES dimensional.dim_tipo_gestao(id_tipo_gestao) ON DELETE RESTRICT,
    id_nivel_hierarquia         INTEGER REFERENCES dimensional.dim_nivel_hierarquia(id_nivel_hierarquia) ON DELETE RESTRICT,
    id_esfera_administrativa    INTEGER REFERENCES dimensional.dim_esfera_administrativa(id_esfera_administrativa) ON DELETE RESTRICT,
    id_tipo_unidade             INTEGER REFERENCES dimensional.dim_tipo_unidade(id_tipo_unidade) ON DELETE RESTRICT,
    id_natureza_juridica        INTEGER REFERENCES dimensional.dim_natureza_juridica(id_natureza_juridica) ON DELETE RESTRICT,
    st_centro_obstetrico        BOOLEAN DEFAULT FALSE,
    st_centro_neonatal          BOOLEAN DEFAULT FALSE,
    st_atend_hospitalar         BOOLEAN DEFAULT FALSE,
    st_servico_apoio            BOOLEAN DEFAULT FALSE,
    st_atend_ambulatorial       BOOLEAN DEFAULT FALSE,
    co_motivo_desab             VARCHAR(20),
    co_ambulatorial_sus         VARCHAR(20),
    CONSTRAINT uq_dim_estabelecimento_cnes UNIQUE (codigo_cnes)
);

CREATE INDEX idx_dim_estabelecimento_id_municipio ON dimensional.dim_estabelecimento_saude(id_municipio);
CREATE INDEX idx_dim_estabelecimento_id_natureza ON dimensional.dim_estabelecimento_saude(id_natureza_organizacao);
CREATE INDEX idx_dim_estabelecimento_id_gestao ON dimensional.dim_estabelecimento_saude(id_tipo_gestao);
CREATE INDEX idx_dim_estabelecimento_nome ON dimensional.dim_estabelecimento_saude(nome_estabelecimento);

COMMENT ON TABLE dimensional.dim_estabelecimento_saude IS 'Estabelecimentos de saúde (CNES), com sub-dimensões snowflake';

-- ============================================================================
-- 4. Dim_Bairro (independente)
-- ============================================================================
CREATE TABLE dimensional.dim_bairro (
    id_bairro    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_bairro  VARCHAR(100) NOT NULL,
    CONSTRAINT uq_dim_bairro_nome UNIQUE (nome_bairro)
);

COMMENT ON TABLE dimensional.dim_bairro IS 'Bairros (nome apenas, sem vínculo direto com município na dimensão)';

-- ============================================================================
-- 5. Dim_Tempo
-- ============================================================================
CREATE TABLE dimensional.dim_tempo (
    id_tempo        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_completa   DATE NOT NULL,
    dia             INTEGER NOT NULL,
    mes             INTEGER NOT NULL,
    ano             INTEGER NOT NULL,
    trimestre       INTEGER NOT NULL,
    semestre        INTEGER NOT NULL,
    CONSTRAINT uq_dim_tempo_data UNIQUE (data_completa),
    CONSTRAINT chk_dim_tempo_dia CHECK (dia BETWEEN 1 AND 31),
    CONSTRAINT chk_dim_tempo_mes CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT chk_dim_tempo_trimestre CHECK (trimestre BETWEEN 1 AND 4),
    CONSTRAINT chk_dim_tempo_semestre CHECK (semestre BETWEEN 1 AND 2)
);

CREATE INDEX idx_dim_tempo_ano ON dimensional.dim_tempo(ano);
CREATE INDEX idx_dim_tempo_ano_mes ON dimensional.dim_tempo(ano, mes);

COMMENT ON TABLE dimensional.dim_tempo IS 'Dimensão calendário (2014-2023+)';

-- ============================================================================
-- 6. Dim_FaixaEtaria
-- ============================================================================
CREATE TABLE dimensional.dim_faixa_etaria (
    id_faixa_etaria  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faixa            VARCHAR(10) NOT NULL,
    idade_min        INTEGER NOT NULL,
    idade_max        INTEGER NOT NULL,
    CONSTRAINT uq_dim_faixa_etaria UNIQUE (faixa),
    CONSTRAINT chk_dim_faixa_etaria_min_max CHECK (idade_min <= idade_max)
);

COMMENT ON TABLE dimensional.dim_faixa_etaria IS 'Faixas etárias: 10-14, 15-19, ..., 45-49, 50+';

-- ============================================================================
-- 7. Dim_RacaCor
-- ============================================================================
CREATE TABLE dimensional.dim_raca_cor (
    id_raca_cor  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo       INTEGER NOT NULL,
    descricao    VARCHAR(20) NOT NULL,
    CONSTRAINT uq_dim_raca_cor_codigo UNIQUE (codigo)
);

COMMENT ON TABLE dimensional.dim_raca_cor IS '1-Branca, 2-Preta, 3-Amarela, 4-Parda, 5-Indígena';

-- ============================================================================
-- 8. Dim_LocalOcorrencia (LOCOCOR)
-- ============================================================================
CREATE TABLE dimensional.dim_local_ocorrencia (
    id_local_ocorrencia  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo               INTEGER NOT NULL,
    descricao            VARCHAR(50) NOT NULL,
    CONSTRAINT uq_dim_local_ocorrencia_codigo UNIQUE (codigo)
);

COMMENT ON TABLE dimensional.dim_local_ocorrencia IS '1-Hospital, 2-Outros est. saúde, 3-Domicílio, 4-Via pública, 5-Outros, 6-Aldeia indígena, 9-Ignorado';

-- ============================================================================
-- 9. Dim_SituacaoGestacionalObito (TPMORTEOCO)
-- ============================================================================
CREATE TABLE dimensional.dim_situacao_gestacional_obito (
    id_situacao_gestacional  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                   INTEGER NOT NULL,
    descricao                VARCHAR(60) NOT NULL,
    CONSTRAINT uq_dim_sit_gestacional_codigo UNIQUE (codigo)
);

COMMENT ON TABLE dimensional.dim_situacao_gestacional_obito IS '1-Na gravidez, 2-No parto, 3-No abortamento, 4-Até 42 dias pós-parto, 5-43d a 1 ano, 8-Não ocorreu, 9-Ignorado';

-- ============================================================================
-- 10. Dim_TipoParto (PARTO)
-- ============================================================================
CREATE TABLE dimensional.dim_tipo_parto (
    id_tipo_parto  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo         INTEGER NOT NULL,
    descricao      VARCHAR(20) NOT NULL,
    CONSTRAINT uq_dim_tipo_parto_codigo UNIQUE (codigo)
);

COMMENT ON TABLE dimensional.dim_tipo_parto IS '1-Vaginal, 2-Cesáreo, 9-Ignorado';

-- ============================================================================
-- 11. Dim_MomentoObitoParto (OBITOPARTO)
-- ============================================================================
CREATE TABLE dimensional.dim_momento_obito_parto (
    id_momento_obito_parto  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                  INTEGER NOT NULL,
    descricao               VARCHAR(20) NOT NULL,
    CONSTRAINT uq_dim_momento_obito_parto_codigo UNIQUE (codigo)
);

COMMENT ON TABLE dimensional.dim_momento_obito_parto IS '1-Antes, 2-Durante, 3-Depois, 9-Ignorado';

-- ============================================================================
-- 12. Dim_TipoGravidez (GRAVIDEZ)
-- ============================================================================
CREATE TABLE dimensional.dim_tipo_gravidez (
    id_tipo_gravidez  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo            INTEGER NOT NULL,
    descricao         VARCHAR(20) NOT NULL,
    CONSTRAINT uq_dim_tipo_gravidez_codigo UNIQUE (codigo)
);

COMMENT ON TABLE dimensional.dim_tipo_gravidez IS '1-Única, 2-Dupla, 3-Tripla e mais, 9-Ignorada';

-- ============================================================================
-- 13. Dim_SemanaGestacao (SEMAGESTAC)
-- ============================================================================
CREATE TABLE dimensional.dim_semana_gestacao (
    id_semana_gestacao  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faixa               VARCHAR(20) NOT NULL,
    semanas_min         INTEGER NOT NULL,
    semanas_max         INTEGER NOT NULL,
    CONSTRAINT uq_dim_semana_gestacao_faixa UNIQUE (faixa),
    CONSTRAINT chk_dim_semana_gestacao_min_max CHECK (semanas_min <= semanas_max)
);

COMMENT ON TABLE dimensional.dim_semana_gestacao IS 'Faixas: 0-21, 22-27, 28-31, 32-36, 37-41, 42+';

-- ============================================================================
-- 14. Dim_CID (Role-Playing)
-- ============================================================================
CREATE TABLE dimensional.dim_cid (
    id_cid       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo       VARCHAR(6) NOT NULL,
    descricao    VARCHAR(255),
    capitulo     VARCHAR(10),
    CONSTRAINT uq_dim_cid_codigo UNIQUE (codigo)
);

CREATE INDEX idx_dim_cid_capitulo ON dimensional.dim_cid(capitulo);

COMMENT ON TABLE dimensional.dim_cid IS 'Classificação CID-10 (role-playing: causa_basica, causa_materna, causa_basica_original)';

-- ============================================================================
-- 15. TABELA FATO: Fact_MorteMaterna
-- ============================================================================
CREATE TABLE dimensional.fact_morte_materna (
    id_tempo                     INTEGER NOT NULL REFERENCES dimensional.dim_tempo(id_tempo) ON DELETE RESTRICT,
    id_municipio_ocorrencia      INTEGER NOT NULL REFERENCES dimensional.dim_municipio(id_municipio) ON DELETE RESTRICT,
    id_municipio_residencia      INTEGER REFERENCES dimensional.dim_municipio(id_municipio) ON DELETE RESTRICT,
    id_municipio_estabelecimento INTEGER REFERENCES dimensional.dim_municipio(id_municipio) ON DELETE RESTRICT,
    id_bairro_ocorrencia         INTEGER REFERENCES dimensional.dim_bairro(id_bairro) ON DELETE RESTRICT,
    id_estabelecimento_saude     INTEGER REFERENCES dimensional.dim_estabelecimento_saude(id_estabelecimento) ON DELETE RESTRICT,
    id_faixa_etaria              INTEGER REFERENCES dimensional.dim_faixa_etaria(id_faixa_etaria) ON DELETE RESTRICT,
    id_raca_cor                  INTEGER REFERENCES dimensional.dim_raca_cor(id_raca_cor) ON DELETE RESTRICT,
    id_local_ocorrencia          INTEGER REFERENCES dimensional.dim_local_ocorrencia(id_local_ocorrencia) ON DELETE RESTRICT,
    id_situacao_gestacional      INTEGER REFERENCES dimensional.dim_situacao_gestacional_obito(id_situacao_gestacional) ON DELETE RESTRICT,
    id_tipo_parto                INTEGER REFERENCES dimensional.dim_tipo_parto(id_tipo_parto) ON DELETE RESTRICT,
    id_momento_obito_parto       INTEGER REFERENCES dimensional.dim_momento_obito_parto(id_momento_obito_parto) ON DELETE RESTRICT,
    id_tipo_gravidez             INTEGER REFERENCES dimensional.dim_tipo_gravidez(id_tipo_gravidez) ON DELETE RESTRICT,
    id_semana_gestacao           INTEGER REFERENCES dimensional.dim_semana_gestacao(id_semana_gestacao) ON DELETE RESTRICT,
    id_causa_basica              INTEGER NOT NULL REFERENCES dimensional.dim_cid(id_cid) ON DELETE RESTRICT,
    id_causa_materna             INTEGER REFERENCES dimensional.dim_cid(id_cid) ON DELETE RESTRICT,
    id_causa_basica_original     INTEGER REFERENCES dimensional.dim_cid(id_cid) ON DELETE RESTRICT,
    sexo                         CHAR(1),
    recebeu_assistencia_medica   BOOLEAN,
    quantidade_obitos            INTEGER NOT NULL DEFAULT 1,
    -- Chave primária composta: grão = combinação única de dimensões
    CONSTRAINT pk_fact_morte_materna PRIMARY KEY (
        id_tempo,
        id_municipio_ocorrencia,
        id_causa_basica,
        COALESCE(id_municipio_residencia, 0),
        COALESCE(id_municipio_estabelecimento, 0),
        COALESCE(id_bairro_ocorrencia, 0),
        COALESCE(id_estabelecimento_saude, 0),
        COALESCE(id_faixa_etaria, 0),
        COALESCE(id_raca_cor, 0),
        COALESCE(id_local_ocorrencia, 0),
        COALESCE(id_situacao_gestacional, 0),
        COALESCE(id_tipo_parto, 0),
        COALESCE(id_momento_obito_parto, 0),
        COALESCE(id_tipo_gravidez, 0),
        COALESCE(id_semana_gestacao, 0),
        COALESCE(id_causa_materna, 0),
        COALESCE(id_causa_basica_original, 0),
        COALESCE(sexo, 'X'),
        COALESCE(recebeu_assistencia_medica::INTEGER, -1)::BOOLEAN
    ),
    CONSTRAINT chk_fact_sexo CHECK (sexo IN ('F', 'M', 'I'))
);

-- Índices para performance analítica
CREATE INDEX idx_fact_morte_tempo           ON dimensional.fact_morte_materna(id_tempo);
CREATE INDEX idx_fact_morte_municipio_oc    ON dimensional.fact_morte_materna(id_municipio_ocorrencia);
CREATE INDEX idx_fact_morte_municipio_res   ON dimensional.fact_morte_materna(id_municipio_residencia);
CREATE INDEX idx_fact_morte_causa_basica    ON dimensional.fact_morte_materna(id_causa_basica);
CREATE INDEX idx_fact_morte_causa_materna   ON dimensional.fact_morte_materna(id_causa_materna);
CREATE INDEX idx_fact_morte_faixa_etaria    ON dimensional.fact_morte_materna(id_faixa_etaria);
CREATE INDEX idx_fact_morte_raca_cor        ON dimensional.fact_morte_materna(id_raca_cor);
CREATE INDEX idx_fact_morte_estabelecimento ON dimensional.fact_morte_materna(id_estabelecimento_saude);
CREATE INDEX idx_fact_morte_sexo            ON dimensional.fact_morte_materna(sexo);

COMMENT ON TABLE dimensional.fact_morte_materna IS 'Fato de mortalidade materna — grão: combinação única de dimensões. measure: quantidade_obitos (COUNT)';
COMMENT ON COLUMN dimensional.fact_morte_materna.sexo IS 'F=Feminino, M=Masculino, I=Ignorado. Normalizado no ETL.';
COMMENT ON COLUMN dimensional.fact_morte_materna.quantidade_obitos IS 'Medida: contagem de óbitos para aquela combinação de dimensões';

-- ============================================================================
-- 16. TABELA DE METADADOS: dim_carga (tracking de ETL)
-- ============================================================================
CREATE TABLE dimensional.dim_carga (
    id_carga       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_tabela    VARCHAR(100) NOT NULL,
    tipo_operacao  VARCHAR(20) NOT NULL,  -- 'FULL_REFRESH', 'INCREMENTAL'
    status         VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',  -- 'PENDENTE', 'EM_EXECUCAO', 'CONCLUIDO', 'ERRO'
    registros_inseridos  INTEGER DEFAULT 0,
    registros_atualizados INTEGER DEFAULT 0,
    registros_excluidos   INTEGER DEFAULT 0,
    mensagem_erro    TEXT,
    iniciado_em     TIMESTAMP WITH TIME ZONE,
    finalizado_em   TIMESTAMP WITH TIME ZONE,
    criado_em       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT chk_dim_carga_operacao CHECK (tipo_operacao IN ('FULL_REFRESH', 'INCREMENTAL')),
    CONSTRAINT chk_dim_carga_status CHECK (status IN ('PENDENTE', 'EM_EXECUCAO', 'CONCLUIDO', 'ERRO'))
);

CREATE INDEX idx_dim_carga_tabela ON dimensional.dim_carga(nome_tabela);
CREATE INDEX idx_dim_carga_status ON dimensional.dim_carga(status);

COMMENT ON TABLE dimensional.dim_carga IS 'Metadados de carga das dimensões — auditoria de quando cada tabela foi populada';

-- ============================================================================
-- GRANT DE PERMISSÕES (opcional — descomentar conforme necessidade)
-- ============================================================================
-- GRANT USAGE ON SCHEMA dimensional TO etl_user;
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA dimensional TO etl_user;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA dimensional TO etl_user;

COMMIT;